library("sqldf")
mesql<- "select * from file where Date = '1/2/2007' or Date = '2/2/2007'"
medata<- read.csv.sql("household_power_consumption.txt", sql= mesql,sep=";")
medata$Date<- as.Date(medata$Date, format= "%d/%m/%Y")
dt<- paste(medata$Date, medata$Time, sep=" ")
medata$Time<- strptime(medata$Time, format="%Y-%m-%d %H:%M:%S")
medata$datetime<- as.POSIXct(dt)
png("plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(medata$datetime,medata$Global_active_power,xlab="",ylab="Global Active Power (kilowatt)",type="l")
plot(medata$datetime,medata$Sub_metering_1,xlab="", ylab="Energy sub metering", type="n" )
points(medata$datetime,medata$Sub_metering_1,col="black",type="l")
points(medata$datetime,medata$Sub_metering_2,col="red",type="l")
points(medata$datetime,medata$Sub_metering_3,col="blue",type="l")
legend("topright", c("sub_metering_1", "sub_metering_2", "sub_metering_3"),lty=1,col=c("black","red","blue"))
with(medata, plot(datetime,Voltage,type="l"))
with(medata, plot(datetime, Global_reactive_power,type="l"))
dev.off()