library("sqldf")
mesql<- "select * from file where Date = '1/2/2007' or Date = '2/2/2007'"
medata<- read.csv.sql("household_power_consumption.txt", sql= mesql,sep=";")
medata$Date<- as.Date(medata$Date, format= "%d/%m/%Y")
dt<- paste(medata$Date, medata$Time, sep=" ")
medata$Time<- strptime(medata$Time, format="%Y-%m-%d %H:%M:%S")
medata$datetime<- as.POSIXct(dt)
png("plot3.png",width=480,height=480)
plot(medata$datetime,medata$Sub_metering_1,xlab="", ylab="Energy sub metering", type="n" )
points(medata$datetime,medata$Sub_metering_1,col="black",type="l")
points(medata$datetime,medata$Sub_metering_2,col="red",type="l")
points(medata$datetime,medata$Sub_metering_3,col="blue",type="l")
legend("topright", c("sub_metering_one", "sub_metering_two", "sub_metering_three"),lty=1,col=c("black","red","blue"))
dev.off()